#:schema node_modules/wrangler/config-schema.json
name = "telegram-miniapp-template"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
# [placement]
# mode = "smart"


# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/pages/functions/bindings/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/pages/functions/bindings/#secrets
# [vars]
# MY_VARIABLE = "production_value"

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#workers-ai
# [ai]
# binding = "AI"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
# [[d1_databases]]
# binding = "telegram-miniapp-template"
# database_name = "my-database"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"
# script_name = 'my-durable-object'

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
# KV Example:
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#queue-producers
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides

[[d1_databases]]
binding = "DB"
database_name = "telegram-miniapp-template-test"
database_id = "070cb992-8d58-4897-92f8-2fdf3527e9ae"

######## PREVIEW environment config ########
[env.preview.vars]
# API_KEY = "xyz789"
NODE_VERSION = "18.17.0"
NEXT_PUBLIC_BASE_URL="https://test.telegram-miniapp-template.pages.dev/" # api serer url
# NEXT_PUBLIC_IMG_BASE_URL=https://test.xxx # custom image loader url
# BOT_TOKEN="xxx" # telegram bot token
# NEXT_PUBLIC_TG_MINIAPP_TONCONNECT_MANIFEST_URL="https://test.tg.characterx.ai/tonconnect-manifest-dev.json" # ton connect manifest url
NEXT_PUBLIC_TG_MINIAPP_URL="https://t.me/xxx" # telegram miniapp url

[[env.preview.d1_databases]]
binding = "DB"
database_name = "telegram-miniapp-template-test"
database_id = "070cb992-8d58-4897-92f8-2fdf3527e9ae"


# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

[env.production.vars]
# API_KEY = "abc123"
NODE_VERSION = "18.17.0"
NEXT_PUBLIC_BASE_URL="https://telegram-miniapp-template.pages.dev/" # api serer url
# NEXT_PUBLIC_IMG_BASE_URL=https://xxx # custom image loader url
# BOT_TOKEN="xxx" # telegram bot token
# NEXT_PUBLIC_TG_MINIAPP_TONCONNECT_MANIFEST_URL="https://xxx" # ton connect manifest url
NEXT_PUBLIC_TG_MINIAPP_URL="https://t.me/xxx" # telegram miniapp url

[[env.production.d1_databases]]
binding = "DB"
database_name = "telegram-miniapp-template"
database_id = "c9c45843-c867-40b0-8cac-35397c5aa741"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
